name: 'Instalando Qemu'
author: 'Colorados Team'
description: 'Instalación de qemu pensada en PintOS'
runs:
  using: 'composite'
  steps:
    - run: |
        sudo apt-get install qemu
        sudo apt-get install -y bridge-utils resolvconf
        sudo apt-get update 
        sudo apt-get install -y qemu-kvm qemu virt-manager virt-viewer libvirt-bin
      shell: 'bash'

