name: 'Calificación de las fases del proyecto'

on: 
  push:
    branches: ['master', 'develop']
  pull_request:
    branches: ['master', 'develop']

jobs:
  threads:
    name: 'Fase: Threads'
    runs-on: 'ubuntu-16.04'
    env:
      phase: 'threads'
    steps:
      - name: 'Clonando repositorio'
        uses: 'actions/checkout@v2'
      - name: 'Instalando Qemu'
        uses: './.github/qemu-install'
      - name: 'Configurando entorno y ejecutando tests'
        uses: './.github/env-config'
        with:
          phase: '${{ env.phase }}'
      - name: 'Score'
        working-directory: '/home/runner/pintos/${{ env.phase }}/build'
        run: 'cat grade'

  userprog:
    name: 'Fase: User Programs'
    runs-on: 'ubuntu-16.04'
    env:
      phase: 'userprog'
    steps:
      - name: 'Clonando repositorio'
        uses: 'actions/checkout@v2'
      - name: 'Instalando Qemu'
        uses: './.github/qemu-install'
      - name: 'Configurando entorno y ejecutando tests'
        uses: './.github/env-config'
        with:
          phase: '${{ env.phase }}'
      - name: 'Score'
        working-directory: '/home/runner/pintos/${{ env.phase }}/build'
        run: 'cat grade'

  vm:
    name: 'Fase: Virtual Memory'
    runs-on: 'ubuntu-16.04'
    env:
      phase: 'vm'
    steps:
      - name: 'Clonando repositorio'
        uses: 'actions/checkout@v2'
      - name: 'Instalando Qemu'
        uses: './.github/qemu-install'
      - name: 'Configurando entorno y ejecutando tests'
        uses: './.github/env-config'
        with:
          phase: '${{ env.phase }}'
      - name: 'Score'
        working-directory: '/home/runner/pintos/${{ env.phase }}/build'
        run: 'cat grade'

  filesys:
    name: 'Fase: File System'
    runs-on: 'ubuntu-16.04'
    env:
      phase: 'filesys'
    steps:
      - name: 'Clonando repositorio'
        uses: 'actions/checkout@v2'
      - name: 'Instalando Qemu'
        uses: './.github/qemu-install'
      - name: 'Configurando entorno y ejecutando tests'
        uses: './.github/env-config'
        with:
          phase: '${{ env.phase }}'
      - name: 'Score'
        working-directory: '/home/runner/pintos/${{ env.phase }}/build'
        run: 'cat grade'
