name: 'Configuración de Ambiente'
author: 'Colorados team'
description: 'Preparación de ambiente para correr proyecto pintos'
# Entradas para la configuración
inputs:
  src:
    description: 'root de las carpetas de las fases de PintOS relativo al repositorio'
    required: false 
    default: '/'
  phase:
    description: 'nombre de la carpeta (threads, userprog, vm, filesys)'
    required: true
# Pasos para configurar el ambiente
runs:
  using: 'composite'
  steps:
    - name: 'Crear enlace hacia home'
      shell: 'bash'
      run: 'ln -s  `pwd`$src ~/pintos'
    - name: 'Compilar utilidades'
      shell: 'bash'
      run: |
        cd ~/pintos/utils
        make
    - name: 'Compilar tests'
      shell: 'bash'
      working-directory: '/home/runner/pintos/${{ inputs.phase }}/'
      run: 'make'
    - name: 'Ejecutar tests'
      shell: 'bash'
      working-directory: '/home/runner/pintos/${{ inputs.phase }}/build'
      env:
        PINTOSPH: ${{ inputs.phase }}
      run: |
        PATH=$PATH:~/pintos/utils
        make grade

